"use strict";
const assert=require("node:assert/strict");
const {CLASS,classify,cohort}=require("./human-telemetry-classifier.js");
const base={drops:100,tens2:10,tens3:8,chains2:0,chains3:0,maxChain:0,firstChainDrop:null,chainsAfterFirst:0,chainEvents:[],sessionRestarts:0};
assert.equal(classify({...base,drops:59}).class,CLASS.INCOMPLETE);
assert.equal(classify({...base,drops:35},{gameOver:true}).class,CLASS.NO_DISCOVERY);
assert.equal(classify(base).class,CLASS.NO_DISCOVERY);
let incidental={...base,chains2:1,maxChain:2,firstChainDrop:40,chainEvents:[{drop:40,level:3,depth:2}]};
assert.equal(classify(incidental).class,CLASS.INCIDENTAL);
let emerging={...incidental,chains2:2,chainsAfterFirst:1,chainEvents:[...incidental.chainEvents,{drop:70,level:4,depth:2}]};
assert.equal(classify(emerging).class,CLASS.EMERGING);
let deliberate={...incidental,drops:120,chains2:3,chainsAfterFirst:2,chainEvents:[...incidental.chainEvents,{drop:70,level:4,depth:2},{drop:100,level:5,depth:2}]};
assert.ok([CLASS.DELIBERATE,CLASS.STRONG].includes(classify(deliberate).class));
let strong={...incidental,drops:120,chains2:4,chains3:1,maxChain:3,chainsAfterFirst:3,chainEvents:[...incidental.chainEvents,{drop:70,level:4,depth:2},{drop:90,level:5,depth:3},{drop:110,level:5,depth:2}]};
assert.equal(classify(strong).class,CLASS.STRONG);
// Duplicate same-drop events must fail closed to emerging rather than manufacture mastery.
let dup={...strong,chainsAfterFirst:3,chainEvents:[incidental.chainEvents[0],{drop:70,level:4,depth:2},{drop:70,level:4,depth:3},{drop:90,level:5,depth:3}]};
assert.equal(classify(dup).class,CLASS.EMERGING);
assert.equal(classify(strong,{automated:true}).class,CLASS.INCOMPLETE);
assert.equal(classify({...strong,sessionRestarts:1}).class,CLASS.INCOMPLETE);
assert.equal(classify({...strong,firstChainDrop:41}).class,CLASS.INCOMPLETE);
assert.equal(classify({...strong,chains2:99}).class,CLASS.INCOMPLETE);
assert.equal(classify({...strong,chainEvents:[...strong.chainEvents,{drop:121,level:5,depth:2}],chains2:5,chainsAfterFirst:4}).class,CLASS.INCOMPLETE);
const c=cohort([classify(strong),classify(deliberate),classify(strong),classify(base),classify(incidental)]);
assert.equal(c.freezeDirectional,true);
const weak=cohort([classify(strong),classify(base),classify(base),classify(incidental),classify(emerging)]);
assert.equal(weak.freezeDirectional,false);
console.log("Human telemetry adversarial gate: PASS");
